# Thông tin k?t n?i Database
db.url = jdbc:mysql://sql12.freesqldatabase.com:3306/sql12828332?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Ho_Chi_Minh&useSSL=false&allowPublicKeyRetrieval=true
db.user = sql12828332
db.pass = lBL6xIvN17